### ISSUE TITLE
Verbindungs Problem

### ISSUE THREAD

**Issue by Armin46** [MeisterTR/ioBroker.worx#14]
Hallo,

erstmal Klasse das du einen neuen Adapter erstellt hast.

ich habe aber leider ein Verbindungsproblem.
Im Log steht folgendes:

host.raspberrypi | 2019-06-29 12:29:49.844 | error | instance system.adapter.worx.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2019-06-29 12:29:49.844 | error | Caught by controller[0]:     at startup (bootstrap_node.js:160:9)
host.raspberrypi | 2019-06-29 12:29:49.844 | error | Caught by controller[0]:     at run (bootstrap_node.js:394:7)
host.raspberrypi | 2019-06-29 12:29:49.844 | error | Caught by controller[0]:     at Module.runMain (module.js:611:10)
host.raspberrypi | 2019-06-29 12:29:49.844 | error | Caught by controller[0]:     at Function.Module._load (module.js:445:3)
host.raspberrypi | 2019-06-29 12:29:49.844 | error | Caught by controller[0]:     at tryModuleLoad (module.js:453:12)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]:     at Module.load (module.js:494:32)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]:     at Object.Module._extensions..js (module.js:586:10)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]:     at Module._compile (module.js:549:28)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]:     at Object.runInThisContext (vm.js:97:10)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]:     at createScript (vm.js:56:10)
host.raspberrypi | 2019-06-29 12:29:49.843 | error | Caught by controller[0]: SyntaxError: Unexpected token ...
host.raspberrypi | 2019-06-29 12:29:49.842 | error | Caught by controller[0]:             ^^^
host.raspberrypi | 2019-06-29 12:29:49.842 | error | Caught by controller[0]:             ...options,
host.raspberrypi | 2019-06-29 12:29:49.838 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65

gibts hierfür eine Lösung ?

Grüße Armin

**Comment by Armin46** [comment]
Hab es selbst hin bekommen.
Node IO Brocker und NPM aktuallisert und es läuft
