### ISSUE TITLE
mehrere Mäher verursachen ausfall

### ISSUE THREAD

**Issue by Tommy-LSA** [MeisterTR/ioBroker.worx#16]
Ich habe den Adapter installiert und er funktionierte ugf. 2 Stunden lang. Jetzt kommt im Log nur noch:

`2019-07-15 15:17:43.345  - [31merror[39m: worx.0 ERROR: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"`

Ich finde leider kein Setting, was den Adapter mehr "chatty" bezüglich debugmeldungen macht.
Mein Account ist nicht gesperrt, die Handy App funktioniert einwandfrei. Falls ich irgendwelche Infos liefern soll, einfach sagen. IO Broker ist ziemlich aktuell und Node ist in Version 10

**Comment by MeisterTR** [comment]
Auch wen du mit dem Handy im selben WLAN bist wie der Adapter? Habe die Vermutung dass worx ips aussperrt wenn zu viele Anfragen kommen. Lass den Adapter mal 24 Stunden ruhen und versuche es erneut.

**Comment by Tommy-LSA** [comment]
Japp, ich bin mit dem Handy im gleichen Heimnetz. Handy über Wifi, Raspi mit ioBroker über Kabel am gleichen Router. Also, von extern gesehen, die gleiche IP. Ich habe 3 Mäher registriert, von denen 2 aktiv sind. Nummer 3 fährt woanders, ohne WLAN und liefert schon über ein Jahr keine Daten in die Cloud.
Ich habe beim Adapter jetzt erstmal "Pause" gedrückt.

Ich habe gerade mal noch die Windows App aus dem Robo Forum getestet. Die sagt auch 403. :(
Scheinbar hat Worx gerade ein Problem. Wenn man sich auf der Landroid Webseite anmelden möchte, kommt ebenfalls dieses "Forbidden" schon beim aufrufen der Seite https://account.worxlandroid.com/login

**Comment by Tommy-LSA** [comment]
Fehlermeldung, welche den Adapter jedes mal neu starten lässt. Vielleich verursacht das irdendwann den IP lock?

`2019-07-15 18:00:33.434  - [32minfo[39m: worx.0 cleaned everything up...
2019-07-15 18:00:33.660  - [31merror[39m: Caught by controller[0]: (node:10062) UnhandledPromiseRejectionWarning: StatusCodeError: 422 - {"message":"Missing coordinates","code":"422.005"}
2019-07-15 18:00:33.661  - [31merror[39m: Caught by controller[0]:     at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15)
2019-07-15 18:00:33.662  - [31merror[39m: Caught by controller[0]:     at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33)
2019-07-15 18:00:33.662  - [31merror[39m: Caught by controller[0]:     at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
2019-07-15 18:00:33.662  - [31merror[39m: Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
2019-07-15 18:00:33.662  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:189:13)
2019-07-15 18:00:33.662  - [31merror[39m: Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
2019-07-15 18:00:33.663  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:189:13)
2019-07-15 18:00:33.663  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
2019-07-15 18:00:33.663  - [31merror[39m: Caught by controller[0]:     at Object.onceWrapper (events.js:277:13)
2019-07-15 18:00:33.663  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.emit (events.js:194:15)
2019-07-15 18:00:33.664  - [31merror[39m: Caught by controller[0]:     at endReadableNT (_stream_readable.js:1125:12)
2019-07-15 18:00:33.664  - [31merror[39m: Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-07-15 18:00:33.664  - [31merror[39m: Caught by controller[1]: (node:10062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-07-15 18:00:33.664  - [31merror[39m: Caught by controller[2]: (node:10062) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-07-15 18:00:33.664  - [31merror[39m: Caught by controller[3]: TypeError: Cannot read property 'st' of undefined
2019-07-15 18:00:33.665  - [31merror[39m: Caught by controller[3]:     at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:164:32)
2019-07-15 18:00:33.665  - [31merror[39m: Caught by controller[3]:     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.worx/main.js:107:30)
2019-07-15 18:00:33.665  - [31merror[39m: Caught by controller[3]:     at ontimeout (timers.js:436:11)
2019-07-15 18:00:33.665  - [31merror[39m: Caught by controller[3]:     at tryOnTimeout (timers.js:300:5)
2019-07-15 18:00:33.666  - [31merror[39m: Caught by controller[3]:     at listOnTimeout (timers.js:263:5)
2019-07-15 18:00:33.666  - [31merror[39m: Caught by controller[3]:     at Timer.processTimers (timers.js:223:10)
2019-07-15 18:00:33.666  - [31merror[39m: host.raspberrypi instance system.adapter.worx.0 terminated with code 0 (OK)
2019-07-15 18:00:33.666  - [32minfo[39m: host.raspberrypi Restart adapter system.adapter.worx.0 because enabled
2019-07-15 18:01:03.703  - [32minfo[39m: host.raspberrypi instance system.adapter.worx.0 started with pid 10112
2019-07-15 18:01:09.478  - [32minfo[39m: worx.0 starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.worx, node: v10.15.3
2019-07-15 18:01:09.586  - [32minfo[39m: worx.0 config e-mail: fredfeuerstein@gmx.de
2019-07-15 18:01:09.588  - [32minfo[39m: worx.0 config password: XxxxxxXXXXxxxXXX
2019-07-15 18:01:11.285  - [32minfo[39m: worx.0 sucess conect!
2019-07-15 18:01:13.766  - [32minfo[39m: worx.0 ready
2019-07-15 18:01:13.792  - [32minfo[39m: worx.0 ready
2019-07-15 18:01:15.313  - [32minfo[39m: worx.0 ready
2019-07-15 18:01:17.217  - [31merror[39m: worx.0 uncaught exception: Cannot read property 'st' of undefined
2019-07-15 18:01:17.218  - [31merror[39m: worx.0 TypeError: Cannot read property 'st' of undefined
    at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:164:32)
    at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.worx/main.js:107:30)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-07-15 18:01:17.221  - [32minfo[39m: worx.0 cleaned everything up...
2019-07-15 18:01:18.232  - [32minfo[39m: worx.0 cleaned everything up...
2019-07-15 18:01:18.455  - [31merror[39m: Caught by controller[0]: (node:10112) UnhandledPromiseRejectionWarning: StatusCodeError: 422 - {"message":"Missing coordinates","code":"422.005"}
2019-07-15 18:01:18.456  - [31merror[39m: Caught by controller[0]:     at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15)
2019-07-15 18:01:18.457  - [31merror[39m: Caught by controller[0]:     at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33)
2019-07-15 18:01:18.457  - [31merror[39m: Caught by controller[0]:     at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
2019-07-15 18:01:18.457  - [31merror[39m: Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
2019-07-15 18:01:18.457  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:189:13)
2019-07-15 18:01:18.457  - [31merror[39m: Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
2019-07-15 18:01:18.458  - [31merror[39m: Caught by controller[0]:     at Request.emit (events.js:189:13)
2019-07-15 18:01:18.458  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
2019-07-15 18:01:18.458  - [31merror[39m: Caught by controller[0]:     at Object.onceWrapper (events.js:277:13)
2019-07-15 18:01:18.458  - [31merror[39m: Caught by controller[0]:     at IncomingMessage.emit (events.js:194:15)
2019-07-15 18:01:18.458  - [31merror[39m: Caught by controller[0]:     at endReadableNT (_stream_readable.js:1125:12)
2019-07-15 18:01:18.459  - [31merror[39m: Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-07-15 18:01:18.459  - [31merror[39m: Caught by controller[1]: (node:10112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-07-15 18:01:18.459  - [31merror[39m: Caught by controller[2]: (node:10112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-07-15 18:01:18.459  - [31merror[39m: Caught by controller[3]: TypeError: Cannot read property 'st' of undefined
2019-07-15 18:01:18.460  - [31merror[39m: Caught by controller[3]:     at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:164:32)
2019-07-15 18:01:18.460  - [31merror[39m: Caught by controller[3]:     at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.worx/main.js:107:30)
2019-07-15 18:01:18.460  - [31merror[39m: Caught by controller[3]:     at ontimeout (timers.js:436:11)
2019-07-15 18:01:18.460  - [31merror[39m: Caught by controller[3]:     at tryOnTimeout (timers.js:300:5)
2019-07-15 18:01:18.461  - [31merror[39m: Caught by controller[3]:     at listOnTimeout (timers.js:263:5)
2019-07-15 18:01:18.461  - [31merror[39m: Caught by controller[3]:     at Timer.processTimers (timers.js:223:10)
2019-07-15 18:01:18.461  - [31merror[39m: host.raspberrypi instance system.adapter.worx.0 terminated with code 6 (uncaught exception)
2019-07-15 18:01:18.461  - [32minfo[39m: host.raspberrypi Restart adapter system.adapter.worx.0 because enabled
2019-07-15 18:01:48.490  - [32minfo[39m: host.raspberrypi instance system.adapter.worx.0 started with pid 10159
2019-07-15 18:01:54.182  - [32minfo[39m: worx.0 starting. Version 0.3.1 in /opt/iobroker/node_modules/iobroker.worx, node: v10.15.3
2019-07-15 18:01:54.291  - [32minfo[39m: worx.0 config e-mail: fredfeuerstein@gmx.de
2019-07-15 18:01:54.292  - [32minfo[39m: worx.0 config password: XxxxxxXXXXxxxXXX
2019-07-15 18:01:56.017  - [32minfo[39m: worx.0 sucess conect!
2019-07-15 18:01:58.350  - [32minfo[39m: worx.0 ready
2019-07-15 18:01:58.412  - [32minfo[39m: worx.0 ready
2019-07-15 18:01:58.423  - [32minfo[39m: worx.0 ready
2019-07-15 18:02:02.943  - [31merror[39m: worx.0 uncaught exception: Cannot read property 'st' of undefined
2019-07-15 18:02:02.944  - [31merror[39m: worx.0 TypeError: Cannot read property 'st' of undefined
    at Worx.setStates (/opt/iobroker/node_modules/iobroker.worx/main.js:164:32)
    at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.worx/main.js:107:30)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-07-15 18:02:02.947  - [32minfo[39m: worx.0 cleaned everything up...`

**Comment by Tommy-LSA** [comment]
Nachdem es gestern mit einer neuen IP wieder eine Weile funktioniert hat, kommt jetzt wieder ein 403. Kann es an den Adapter Neustarts (mit verbundenem neuen Login) liegen, das worx da dann dicht macht? Einer der Mäher ist eine alte S-Klasse, der Andere ist eine alte M-Klasse, mit Cloud FW (>5)
Das die App funktioniert war nur eine Täuschung. Das Aktivitätenprotokoll lässt sich nicht abrufen. Was noch geht sind Pushnachrichten, dass hat mich zu der Annahme gebracht, das die App noch läuft.

**Comment by MeisterTR** [comment]
Stelle mal den intervall fürs Wetter ganz hoch also mindestens 12 Stunden. Ich schätze dass drei Mäher zu viele anfangen an den worx Server senden und er dann dicht macht.

**Comment by Tommy-LSA** [comment]
Ich habe bezüglich des Fehlers mal den Trace in der Windows App angeschaut. Wie ich vermutet habe, kommt bei dem Mäher "Foxy", der keine Verbindung zu einem WLAN hat, ein komplett leeres Datenobjekt.

`Status Fixy: {"cfg":{"id":1,"lg":"it","tm":"10:45:28","dt":"16\/07\/2019","sc":{"m":1,"p":0,"d":[["12:00",600,1],["12:00",600,0],["12:00",600,0],["12:00",600,1],["12:00",600,0],["12:00",600,0],["12:00",600,1]]},"cmd":0,"mz":[1,20,0,0],"mzv":[0,1,0,1,0,1,0,1,1,1],"rd":0,"sn":"XXXXXXXX"},"dat":{"mac":"F0FE6B26XXXX","fw":3.51,"bt":{"t":21.9,"v":20.2,"p":100,"nr":4802,"c":0,"m":1},"dmp":[-0.2,-0.5,316.2],"st":{"b":120367,"d":2319370,"wt":132767},"ls":1,"le":0,"lz":2,"rsi":-50,"lk":0}}
Status Foxy: {}
Status Foxy2: {"cfg":{"lg":"de","tm":"10:38:54","dt":"16\/07\/2019","sc":{"m":1,"p":0,"d":[["08:00",840,0],["08:00",840,0],["08:00",840,0],["08:00",840,1],["08:00",840,0],["08:00",840,0],["08:00",840,1]]},"cmd":0,"mz":[0,0,0,0],"mzv":[0,0,0,0,0,0,0,0,0,0],"rd":0,"sn":"XXXXXXXX"},"dat":{"mac":"0023A7A6XXXX","fw":5.21,"bt":{"t":29.7,"v":26.54,"p":80,"nr":105,"c":0},"dmp":[0,1,0],"st":{"b":9440,"d":165436,"wt":10058},"ls":7,"le":0,"lz":2,"rsi":66,"lk":0}}
`
Das fliegt dir in der main.js setStates() um die Ohren. Ich habe mal in die setStates() ganz oben das eingefügt:
`if(!data || !data.dat) return;`
Damit crashed und re-startet der Adapter zumindest nicht mehr. Ich habe mir wieder eine neue IP geholt und lass es mal mit der Modifikation laufen.

Wo soll der Wetter Intervall eingestellt werden? In den Adapter Settings ist nichts außer Mailadresse und Passwort bzw. ein Wert für "Verzögerung für Edgecut in ms"

**Comment by Tommy-LSA** [comment]
Jetzt gibt es ein anderes Problem. Die Verbindung steht und die IP ist auch nicht gelockt. Allerdings kommt nur beim Adapterstart einmalig ein Datenupdate. Dann kommen keine weiteren Werte. Ich weiß nicht, ob ich da jetzt mit der einen Zeile was kaputtgemacht habe, kann es mir aber eigentlich nicht vorstellen. Ich kann mich erinnern, das im Log nach "success connect!" immer noch 3x "ready" kam. Das kommt neuerdings nicht mehr. Das log bleibt nach "success connect!" stehen. Der Adapter steht auf grün und die connection auf "true". Ich kenne den Code zu wenig, als dass ich da selber auf Fehlersuche gehen könnte. Bin aber gern bereit zu testen/helfen

**Comment by Tommy-LSA** [comment]
Im Robo Forum habe ich gerade gelesen, dass man von einer IP aus nicht mit mehreren UUIDs agieren soll, da sonst eine Sperre für 24h ausgelöst wird. In der api.js habe ich gesehen, dass Du bei jedem Adapter start eine neue UUID generierst. Vielleicht ist das auch ein Grund für die Locks. Kannst Du die UUID nicht nur einmal erzeugen, speichern und immer dieselbe verwenden?

Vermutlich hänge ich jetzt gerade in einem solchen 24h Zertifikats lock, der sich nur auf das MQTT auswirkt. Deshalb kommen nach dem initialen Status keine Updates mehr.

In der App muss ich aktuell ein Update manuell anstoßen (Bildschirm runterziehen) um aktuelle Daten zu bekommen. Das würde zum MQTT Lock passen, da sonst der Startbildschirm eigentlich automatisch Up2Date ist.

Quelle:https://www.roboter-forum.com/index.php?thread/22795-entwicklungsprojekt-worx-landroid-kress-mission-desktop-app/&postID=474172#post474172

**Comment by MeisterTR** [comment]
ja genau bei jedem neustart wir eine neue uuid erzeugt, was im Normalfall eigentlich nicht tragisch ist, weil er ja eigentlich immer an ist.  werde mir das mit der festen uuid für die nächste Version notieren. wenn der Adapter natürlich permanent neu startet wegen einem Fehler, dann wird man schnell geblocked. Auch drei Mäher können schon die Nachrichtengrenze von Worxserver knacken wenn man dann auch noch ein bisschen rumprobiert geht das alles sehr schnell, beim Programmieren vom Adapter musste ich auch regelmäßig Zwangspausen machen. 
Die Abfrage ob Daten vorhanden sind ist auf jeden Fall sinnvoll, hatte den Fall bis lang noch nicht. mfg

**Comment by Tommy-LSA** [comment]
Hört sich gut an. Ich habe jetzt erstmal eine uuid hartverdrahtet und werde berichten ob es morgen wieder geht.
Eventuell könntest Du ja, wenn beim initialen Statusrequest ein Mäher nur ein leeres Objekt liefert, diesen auch von irgendwelchen Requests ausschließen. Da wird dann ja eh nichts kommen. Und wie gesagt, das Wetter optional abwählbar, wenn es Datentransfer reduziert. Sind ja bei mehreren Mähern sowieso redundante Daten, wenn die Mäher im gleichen Ort fahren.

Solltest Du irgendwas an Input brauchen, oder jemanden zum testen - kein Problem

**Comment by Tommy-LSA** [comment]
Für kurze Zeit ging es heute wieder. Vielleicht eine Stunde oder so. Das ist doch so nicht wirklich verwendbar. Kann man noch irgendwas an irgendwelchen Abfrageintervallen schrauben um die Sperre zu vermeiden? Wetter habe ich schon komplett deaktiviert indem ich direkt unter UpdateWeather(mower) { ein return gesetzt habe. Dadurch wird m.E. auch kein intervall gesetzt und das Wetter findet nicht statt

**Comment by Tommy-LSA** [comment]
Ich habe grad mal den MQTT Part angeschaut. Auf Worx Seite scheint ja die Verbindung sofort abgebaut zu werden, wenn ein Paket gesendet wurde. Der MQTT client versucht sofort wieder die verbindung aufzubauen und zu subscriben, was natürlich immenns viel zugriffe bedeutet. Probier mal das, dann wird nur alle 10 Sekunden subscribed, was völlig ausreichend ist. Ich habe da grad einen Test laufen, mal gucken, ob ich so noch rausfliege

`const options = {
                pfx: p12,
                clientId: 'android-' + UUID,
                reconnectPeriod: 10000
            };`

**Comment by Tommy-LSA** [comment]
Ich habe jetzt (in einer separaten nodejs Umgebung ohne ioBroker) mal getestet. Eine Anmeldung zum Start, dann nur noch MQTT pollen mit 2 Mähern und einer reconnectPeriod von 20000. Läuft bereits über 24h ohne Sperre. Alles andere habe ich deaktiviert (Wetter, intervall ckeckOnline() usw.)

**Comment by MeisterTR** [comment]
wäre super wenn du das weiterverfolgen würdest, da bei mir das Problem nicht auftritt und nen pullrequest macht. mfg Tobi

**Comment by Tommy-LSA** [comment]
Vermutlich muss das Design grundlegend geändert werden. Momentan nutzt jede mower Instanz eine eigene mqtt Verbindung. Der Server erlaubt aber anscheinend nur eine Verbindung. Im Resultat wirft jeder mower, der die Verbindung aufbaut den aktuell verbundenen raus (that.mqttC.on('offline', function () {). Im derzeitigen Zustand versucht der MQTT Client des rausgeworfenen mowers sofort wieder neu zu connecten, was zu einem Amoklauf führt bis der Server die Notbremse zieht. Ich hatte das entschärft mit reconnectPeriod: 20000, dass sorgte wenigstens für 20 Sekunden Pause zwischen den reconnects. Irgendwann > 24h wird man aber trotzdem gesperrt. **Der Adapter, in aktueller Git Version ist nicht in der Lage, mehrere Mäher zu handlen**. Bei einem Mäher funktioniert das Ganze wahrscheinlich. Das muss also Grundlegend umgebaut werden, sodass nur ein MQTT Client auf den Server connected und man auf dieser Connection alle Mäher subscribed. Auch die publishes müssen über diese Verbindung gemacht werden. Über das topic kann man dann ja forken `that.mqttC.on('message', function (topic, message) {
                console.log(that.serial + ": Topic: " + topic);}`
Ich habe momentan einen Codeschnipsel laufen, bei dem das so gelöst ist (Alle Mäher nutzen eine MQTT Verbindung). Ich habe auch nur subscribed und mache gar keinen publish zum pollen. In dem Fall kommen von den Mäher alle ca. 5 Minuten Daten oder wenn sich der Status ändert halt sofort. Ich habe momentan recht wenig Zeit, das alles umzubauen und einen pullrequest vorzubereiten. Ich habe das bei mir in einem Docker Container (ohne ioBroker), der mir die Statusmeldungen einfach an meinen mosquitto durchgibt, auf dem FHEM subscribed hat

**Comment by MeisterTR** [comment]
ok danke für die ausführliche Erklärung, da ich nur einen Mäher habe, ist mir das nicht aufgefallen. Jetzt macht es aber auch sinn, dass die app dann nur noch im poll Berieb arbeitet. ich dachte immer dass es egal ist wie viele clients verbunden sind und habe es auch nciht weiter untersucht, werde die tage mal alles etwas umstricken. danke nochmal....

**Comment by Tommy-LSA** [comment]
Ich habe das aktuell wie folgt bei mir (ohne ioBroker) laufen. Das subscribed aber nur alle Mäher und wartet, das sie von sich aus was senden. Das tun sie all 5 Minuten und zusätzlich wenn sich der Status ändert. Wenn Du kitzeln willst, musst Du in irgend einem Intervall ein leeres publish auf das topic des jeweiligen Mähers machen. Wetter und alles andere habe ich mir nicht angeschaut

Hier der umgebaute Konstruktor der Worxcloud Klasse. Gibt sicher noch andere Ansätze

```
class Worx extends EventEmitter {
    constructor(username, password) {
        super();
        //let mower = [];
        this.USER = username;
        this.PASS = password;
        this.mower = [];
        this.interval = 5000; //3600000;
        this._getticket((err, data) => {
            let that = this;
            if (err) return;

            that.UserData().then(data => {
                that.UserData = data;               
                MqttServer = data.mqtt_endpoint;

                console.log("Userdata: " + JSON.stringify(data))

                that.UserCert().then(data => {
                    that.UserCert = data;
                    
                    //buffer cert in p12
                    if (typeof Buffer.from === 'function') { // Node 6+
                        try {
                            p12 = Buffer.from(data.pkcs12, 'base64');
                        } catch (e) {
                            console.log('Warning Buffer function  is empty, try new Buffer');
                            p12 = new Buffer(data.pkcs12, 'base64');
                        }
        
                    } else {
                        p12 = new Buffer(data.pkcs12, 'base64');
                    }

                    that.UserDevices().then(data => {
                        that.UserDevices = data;

                        // mqtt connection
                        const options = {
                            pfx: p12,
                            clientId: 'android-' + UUID,
                            reconnectPeriod: 30000,
                            clear:true
                        };

                        var mqtt = require('mqtt');
                        that.mqttC = mqtt.connect('mqtts://' + MqttServer, options);

                        that.mqttC.on('disconnect', function (packet) {
                            console.log("Worxcloud MQTT disconnect")
                            console.log(packet)
                        })

                        that.mqttC.on('offline', function () {
                            console.log("Worxcloud MQTT offline")
                        })

                        that.mqttC.on('connect', function (connack) {
                            //console.log(connack)
                            console.log("Worxcloud MQTT subscribe now to: " + that.mqtt_command_out)
                            

                            data.forEach(function (element, index) {
                                const mow = new mower_new(element);
                                that.mower.push(mow);
                                console.log("subscribe to " + mow.mqtt_command_out)
                                that.mqttC.subscribe(mow.mqtt_command_out);
                                that.emit('found', mow); 
                            });



                        });

                        that.mqttC.on('message', function (topic, message) {
                            console.log("Worxcloud MQTT Toppic: " + topic);
                            let data = JSON.parse(message);
                            that.message = data;
                            that.mower.forEach(function(element,index){
                                if(element.mqtt_command_out === topic){
                                    that.emit('mqtt', element, data);
                                }
                            })
                        });
            
                        that.mqttC.on('packetsend', function (packet) {
                            console.log("Worxcloud MQTT packetsend: " + JSON.stringify(packet));
                        });
            
                        that.mqttC.on('packetreceive', function (packet) {
                            console.log("Worxcloud MQTT packetreceive: " + JSON.stringify(packet));
                        });
            
                        that.mqttC.on('error', function () {
                            reject(new Error(that.serial + ": MQTT ERROR"));
                        });

                        //that.interval = setInterval(that.ckeckOnline.bind(that), 60000);

                    }).catch(err => {
                        console.log(err);
                    });

                }).catch(err => {
                    console.log(err);
                });
            }).catch(err => {
                console.log(err);
            });
        });
    }
```

und hier der passende mower dazu

```
class mower_new extends EventEmitter {
    constructor(data) {
        super();

        if (typeof data === 'undefined' || typeof data !== 'object') {
            throw new Error('options are needed');
        }
        
        this.serial = data.serial_number;
        this.online = data.online;
        this.raw = data;
        this.edgeCut = false;
        this.mqtt_command_in = data.mqtt_topics.command_in;
        this.mqtt_command_out = data.mqtt_topics.command_out;
        console.log('CLASS mit ' + this.serial);
        this.laststate = 0
    }
    /**
     * returns The SN provided by WORX
     * @returns {string} SN of Mower
     */
    getSN() {
        return this.serial;
    }

    getStateChanged(state){
        let retval = this.laststate == state ? false : true;
        this.laststate = state;
        return retval;
    }
}
```

**Comment by MeisterTR** [comment]
so hatte gerade mal ein bisschen zeit um das näher zu untersuchen, du hast vollkommen recht, vor ein paar wochen ging das noch ohne Probleme, scheinbar haben die da wieder mal was geändert. hab bei mir auch neben bei eine iobroker freie Version zum testen laufen. die zeigt auch das von dir beschriebene Verhalten. werde den code in den nächsten Tagen anpassen. danke nochmal...

**Comment by MeisterTR** [comment]
so problem sollte nun gelößt sein
