### ISSUE TITLE
Landroid M500 (WR141E)

### ISSUE THREAD

**Issue by hdering** [MeisterTR/ioBroker.worx#22]
I tried to start your adapter and get the follow error:

```
host.rock64 | 2019-08-25 08:05:01.510 | info | Restart adapter system.adapter.worx.0 because enabled
-- | -- | -- | --
host.rock64 | 2019-08-25 08:05:01.509 | error | instance system.adapter.worx.0 terminated with code 1 ()
Caught | 2019-08-25 08:05:01.508 | error | by controller[0]: at startup (bootstrap_node.js:160:9)
Caught | 2019-08-25 08:05:01.508 | error | by controller[0]: at run (bootstrap_node.js:394:7)
Caught | 2019-08-25 08:05:01.507 | error | by controller[0]: at Module.runMain (module.js:611:10)
Caught | 2019-08-25 08:05:01.507 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2019-08-25 08:05:01.506 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2019-08-25 08:05:01.506 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2019-08-25 08:05:01.505 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2019-08-25 08:05:01.505 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2019-08-25 08:05:01.504 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-08-25 08:05:01.504 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-08-25 08:05:01.504 | error | by controller[0]: SyntaxError: Unexpected token ...
Caught | 2019-08-25 08:05:01.503 | error | by controller[0]: ^^^
Caught | 2019-08-25 08:05:01.503 | error | by controller[0]: ...options,
Caught | 2019-08-25 08:05:01.501 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.worx/main.js:65
```

Do you have any ideas what it could be?

Node.js: v6.17.1
NPM: 3.10.10

**Comment by MeisterTR** [comment]
Yes I know. You have to update node to min 8.xx

**Comment by hdering** [comment]
@MeisterTR your hint was the right. update to 8.16.1 and it works.
