### ISSUE TITLE
Mähzeiten ändern

### ISSUE THREAD

**Issue by metaxa1** [MeisterTR/ioBroker.worx#9]
Hi!
Bin jetzt von der 0.2.0 auf die 0.3.0 umgestiegen.
Ich kann keine Mähzeiten ändern? Sobald ich etawas eintrage, stoppt der Adapter und wird wieder mit den Daten aus der Cloud (App) überschrieben und neu gestartet.

Hier der Log:
```

host.iobroker-master-tb | 2019-06-12 15:11:42.047 | info | Restart adapter system.adapter.worx.0 because enabled
-- | -- | -- | --
host.iobroker-master-tb | 2019-06-12 15:11:42.047 | error | instance system.adapter.worx.0 terminated with code 0 (OK)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at tryOnImmediate (timers.js:768:5)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at runCallback (timers.js:810:20)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3709:38)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at Worx.emit (events.js:214:7)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at emitTwo (events.js:126:13)
Caught | 2019-06-12 15:11:42.047 | error | by controller[0]:     at Worx.onStateChange (/opt/iobroker/node_modules/iobroker.worx/main.js:986:26)
Caught | 2019-06-12 15:11:42.046 | error | by controller[0]:     at Worx.changeMowerCfg (/opt/iobroker/node_modules/iobroker.worx/main.js:1078:35)
Caught | 2019-06-12 15:11:42.046 | error | by controller[0]: TypeError: Cannot set property '0' of undefined
worx.0 | 2019-06-12 15:11:41.964 | info | terminating
worx.0 | 2019-06-12 15:11:41.950 | info | cleaned everything up...
worx.0 | 2019-06-12 15:11:41.948 | error | at processImmediate [as _immediateCallback] (timers.js:745:5)
worx.0 | 2019-06-12 15:11:41.948 | error | at tryOnImmediate (timers.js:768:5)
worx.0 | 2019-06-12 15:11:41.948 | error | at runCallback (timers.js:810:20)
worx.0 | 2019-06-12 15:11:41.948 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3709:38)
worx.0 | 2019-06-12 15:11:41.948 | error | at Worx.emit (events.js:214:7)
worx.0 | 2019-06-12 15:11:41.948 | error | at emitTwo (events.js:126:13)
worx.0 | 2019-06-12 15:11:41.948 | error | at Worx.onStateChange (/opt/iobroker/node_modules/iobroker.worx/main.js:986:26)
worx.0 | 2019-06-12 15:11:41.948 | error | at Worx.changeMowerCfg (/opt/iobroker/node_modules/iobroker.worx/main.js:1078:35)
worx.0 | 2019-06-12 15:11:41.948 | error | TypeError: Cannot set property '0' of undefined
worx.0 | 2019-06-12 15:11:41.947 | error | uncaught exception: Cannot set property '0' of undefined
```

**Comment by mifricke** [comment]
Nicht nur das... Ich kann im Moment keinerlei Datenpunkte ändern. Allerdings ist die App unter iOS im Moment auch nicht richtig funktional. Aktualisierung klappt nur sporadisch und ändern von Mähzeiten klappt auch nicht. Kann das jemand bestätigen?

**Comment by MeisterTR** [comment]
fixed in der 0.3.1

**Comment by metaxa1** [comment]
> fixed in der 0.3.1
bestätigt!
Lieben Dank!
